### ISSUE TITLE
[check-override] prop and overridable methods don't play nice

### ISSUE THREAD

**Issue by carl-stripe** [sorbet/sorbet#1350]
(This bug applies to the `check-override` branch cc @gdritter-stripe)

#### Input

(input is mildly edited from a Stripe-internal example; I hope it still works, but if not I'm happy to share the original)

```ruby
module Opus::Carl
  module A
    sig {overridable.returns(String)}
    def merchant; 'carl'; end
  end

  class B < T::Struct
    prop :merchant, String

    include A
  end
end
```

#### Observed output

```
carl/foo.rb:13: Method Opus::Carl::B#merchant overrides an overridable method Opus::Carl::A#merchant but is not declared with .override http://go/e/5047
    13 |    prop :merchant, String
            ^^^^^^^^^^^^^^^^^^^^^^
    carl/foo.rb:9: defined here
     9 |    def merchant; 'carl'; end
            ^^^^^^^^^^^^
```

#### Expected behavior

I expect this to either work silently, or for there to be some sigil I can place on the `prop` to make this work

**Comment by jez** [comment]
This is fixed. Idk when the fix happened.

https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Opus%3A%3ACarl%0A%20%20module%20A%0A%20%20%20%20extend%20T%3A%3ASig%0A%20%20%20%20sig%20%7Boverridable.returns(String)%7D%0A%20%20%20%20def%20merchant%3B%20'carl'%3B%20end%0A%20%20end%0A%0A%20%20class%20B%20%3C%20T%3A%3AStruct%0A%20%20%20%20prop%20%3Amerchant%2C%20String%0A%0A%20%20%20%20include%20A%0A%20%20end%0Aend

**Comment by iMacTia** [comment]
@jez I just bumped into the same issue, and if you open your Playground link you'll see the error is back now 🤔 
Can we reopen this issue (although it's pretty old!) or should I open a new one?

**Comment by iMacTia** [comment]
Upon closer inspection and comparison with the [docs](https://sorbet.org/docs/tstruct#structs-and-inheritance), I noticed what was missing:
* The module should be an `interface!`;
* Both the getter AND setter should be declared in the module
