### ISSUE TITLE
Instantiate all components of the DispatchResult in SolveConstraint

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#3645]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20ABox%20%3C%20T%3A%3AStruct%0A%20%20include%20Enumerable%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Elem%20%3D%20type_member%0A%0A%20%20prop%20%3Aval%2C%20Elem%0A%0A%20%20sig%20do%0A%20%20%20%20override%0A%20%20%20%20%20%20.params(blk%3A%20T.proc.params(arg0%3A%20Elem).returns(BasicObject))%0A%20%20%20%20%20%20.returns(T.untyped)%0A%20%20end%0A%20%20def%20each(%26blk)%0A%20%20%20%20yield%20self.val%0A%20%20end%0Aend%0A%0Aclass%20BBox%20%3C%20T%3A%3AStruct%0A%20%20include%20Enumerable%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Elem%20%3D%20type_member%0A%20%20prop%20%3Aval%2C%20Elem%0A%0A%20%20sig%20do%0A%20%20%20%20override%0A%20%20%20%20%20%20.params(blk%3A%20T.proc.params(arg0%3A%20Elem).returns(BasicObject))%0A%20%20%20%20%20%20.returns(T.untyped)%0A%20%20end%0A%20%20def%20each(%26blk)%0A%20%20%20%20yield%20self.val%0A%20%20end%0Aend%0A%0Asig%20%7Bparams(box%3A%20T.any(ABox%5BInteger%5D%2C%20BBox%5BString%5D)).void%7D%0Adef%20foo(box)%0A%20%20T.reveal_type(box.map%20%7B%7Cx%7C%20x%7D)%0Aend)

```ruby
# typed: true
extend T::Sig

class ABox < T::Struct
  include Enumerable
  extend T::Sig
  extend T::Generic
  Elem = type_member

  prop :val, Elem

  sig do
    override
      .params(blk: T.proc.params(arg0: Elem).returns(BasicObject))
      .returns(T.untyped)
  end
  def each(&blk)
    yield self.val
  end
end

class BBox < T::Struct
  include Enumerable
  extend T::Sig
  extend T::Generic
  Elem = type_member
  prop :val, Elem

  sig do
    override
      .params(blk: T.proc.params(arg0: Elem).returns(BasicObject))
      .returns(T.untyped)
  end
  def each(&blk)
    yield self.val
  end
end

sig {params(box: T.any(ABox[Integer], BBox[String])).void}
def foo(box)
  T.reveal_type(box.map {|x| x})
end
```

#### Observed output

```
editor.rb:41: Revealed type: T::Array[Integer] https://srb.help/7014
    41 |  T.reveal_type(box.map {|x| x})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:41:
    41 |  T.reveal_type(box.map {|x| x})
                        ^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

The revealed type should be `T.any(Integer, String)`.

- - -

I think this TODO is relevant:

https://github.com/sorbet/sorbet/blob/b97904fb19df3c4b015d4e0e0073522251d9f42a/infer/environment.cc#L1080-L1081

the DispatchResult has multiple components that need to be `T.any` and `T.all`'d together, but we are only taking the main dispatch component.

**Comment by jez** [comment]
This is also a problem with `T.all`, here's another test case:

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20ABox%0A%20%20include%20Enumerable%0A%20%20extend%20T%3A%3AHelpers%0A%20%20interface!%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Elem%20%3D%20type_member%0Aend%0A%0Amodule%20BBox%0A%20%20include%20Enumerable%0A%20%20extend%20T%3A%3AHelpers%0A%20%20interface!%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Elem%20%3D%20type_member%0Aend%0A%0Amodule%20C%3B%20end%0Amodule%20D%3B%20end%0A%0Asig%20%7Bparams(box%3A%20T.all(ABox%5BC%5D%2C%20BBox%5BD%5D)).void%7D%0Adef%20foo(box)%0A%20%20T.reveal_type(box.map%20%7B%7Cx%7C%20x%7D)%0Aend)

```ruby
# typed: true
extend T::Sig

module ABox
  include Enumerable
  extend T::Helpers
  interface!
  extend T::Generic
  Elem = type_member
end

module BBox
  include Enumerable
  extend T::Helpers
  interface!
  extend T::Generic
  Elem = type_member
end

module C; end
module D; end

sig {params(box: T.all(ABox[C], BBox[D])).void}
def foo(box)
  T.reveal_type(box.map {|x| x})
end
```

#### Observed output

```
editor.rb:25: Revealed type: T::Array[C] https://srb.help/7014
    25 |  T.reveal_type(box.map {|x| x})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:25:
    25 |  T.reveal_type(box.map {|x| x})
                        ^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

`T::Array[T.all(C, D)]`

**Comment by froydnj** [comment]
This was fixed in #3653.

**Comment by jez** [comment]
This was closed "prematurely" because the title of the issue was correct, but all the test cases weren't actually test cases of that title. I've opened #5409 with a test case that still reproduces the intended bug, even after the changes in #3653.
